name: social_media_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  shared_preferences: ^2.4.0
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.10
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/